default_model:
  default: resnet18
  mnist: net
  cifar10: resnet18_comp
  cifar100: resnet18_comp
  gtsrb: resnet18_comp
  imagenet16: resnet18_comp

adv_train_iter:
  default: 7

adv_train_alpha:
  default: 0.0078431372549 # 2/255
  mnist: 0.1

adv_train_eps:
  default: 0.031372549 # 8/255
  mnist: 0.3

adv_train_valid_eps:
  default: 0.031372549 # 8/255
  mnist: 0.3
