epochs:
  default: 250
  cifar10: 600
  cifar100: 600
  gtsrb: 600
  imagenet16: 600
lr:
  default: 0.1
  cifar10: 0.025
  cifar100: 0.025
  gtsrb: 0.025
  imagenet16: 0.025
model_ema_steps:
  default: 32
  cifar10: 1
model_ema_decay:
  default: 0.99998
  cifar10: 0.9999
