name: release

on:
  release:
    types: [created]

env:
  DOCKERHUB_REPOSITORY: trojanzoo
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Dump github context
        run: echo "$GITHUB_CONTEXT"
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
  # pypi:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: local0state/base:cpu
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Build
  #       run: |
  #         pip install --upgrade --no-cache-dir setuptools build
  #         python -m build
  #     - name: Publish
  #       uses: pypa/gh-action-pypi-publish@release/v1
  #       with:
  #         user: __token__
  #         password: ${{ secrets.PYPI_API_TOKEN }}
  # cpu:
  #   name: docker-cpu
  #   needs: pypi
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2.3.4
  #     - name: Set up Docker Buildx
  #       id: buildx
  #       uses: docker/setup-buildx-action@v1.6.0
  #     - name: Login to DockerHub
  #       uses: docker/login-action@v1.10.0
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     - name: Login to GitHub Container Registry
  #       uses: docker/login-action@v1.10.0
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.repository_owner }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #     - name: Build and push
  #       uses: docker/build-push-action@v2.7.0
  #       with:
  #         context: ./
  #         file: ./docker/${{ github.job }}.dockerfile
  #         builder: ${{ steps.buildx.outputs.name }}
  #         push: true
  #         tags: |
  #           ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}:${{ github.job }}
  #           ghcr.io/${{ github.repository }}:${{ github.job }}
  #         cache-from: type=gha
  #         cache-to: type=gha
  # gpu:
  #   name: docker-gpu
  #   needs: pypi
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2.3.4
  #     - name: Set up Docker Buildx
  #       id: buildx
  #       uses: docker/setup-buildx-action@v1.6.0
  #     - name: Login to DockerHub
  #       uses: docker/login-action@v1.10.0
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     - name: Login to GitHub Container Registry
  #       uses: docker/login-action@v1.10.0
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.repository_owner }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #     - name: Build and push
  #       uses: docker/build-push-action@v2.7.0
  #       with:
  #         context: ./
  #         file: ./docker/${{ github.job }}.dockerfile
  #         builder: ${{ steps.buildx.outputs.name }}
  #         push: true
  #         tags: |
  #           ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}:${{ github.job }}
  #           ghcr.io/${{ github.repository }}:${{ github.job }}
  #         cache-from: type=gha
  #         cache-to: type=gha
